### ISSUE TITLE
Update static ReadTheDocs pages to correspond with current master

### ISSUE THREAD

**Issue by fluegelk** [Helmholtz-AI-Energy/propulate#105]
At the end of [Tutorial 1, Section 1](https://propulate.readthedocs.io/en/latest/tut_propulator.html), it says "The output looks like this:". However, following only this tutorial up to this point, one would not get any output at all as python's default logging level is `logging.WARNING`, and one is never instructed to set the logging level or call `propulate.utils.set_logger_config()`.

**Comment by mcw92** [comment]
Thanks for your comment! I think this is only the case for the linked ReadTheDocs page which is not yet updated (this will hopefully happen very soon). The actual [script](https://github.com/Helmholtz-AI-Energy/propulate/blob/master/tutorials/propulator_example.py) in the Github repo (which should also be linked on the RTD page at the very top) uses the logger. I will change the title of this issue to "Updating static ReadTheDocs pages to current master stage" and assign myself to it. There will be a complete rework of RTD once other things (parallel checkpointing with hdf5, new solvers, more comprehensive tests, etc.) will be merged and we have a new PyPI release.
