### ISSUE TITLE
Categorical search space of non-strings not behaving correctly

### ISSUE THREAD

**Issue by coquelin77** [Helmholtz-AI-Energy/propulate#109]
Currently the behavior of the propagator is to use the `type` of the first value in the list to determine what kind of selection to do. This will cause issues for a categorical search space of ints.

The first criteria should probably be a test for the length of the space for that parameter instead of the type.

Thoughts?

**Comment by mcw92** [comment]
According to the documentation, this is the expected behavior for now as different types of parameters to be optimized, i.e., continuous, ordinal, and categorical, are encoded via their respective ``Python`` types, i.e., float, int, and str, respectively.
