### ISSUE TITLE
Remove `MPI.COMM_WORLD.barrier()` in `get_data_loaders` function in `torch_example.py`

### ISSUE THREAD

**Issue by mcw92** [Helmholtz-AI-Energy/propulate#113]
In the `torch_example.py` tutorial, the `get_data_loaders` function is called in the `ind_loss` function, i.e., every time an individual is evaluated. However, the `MPI.COMM_WORLD.barrier` in the `get_dataloaders` function, which should prevent conflicts when potentially downloading the dataset for the first time in parallel, imposes an explicit synchronization point during the Propulate optimization, that we definitely do not want to have. This should be fixed / removed.

**Comment by vtotiv** [comment]
A possible solution would be to add an attribute to `get_data_loaders()`, which is set independently for every rank and checked before calling `Barrier()`.

I solved it like this for the two examples in `tutorials/surrogate/`:
```python
    if not hasattr(get_data_loaders, "barrier_called"):
        MPI.COMM_WORLD.Barrier()

        setattr(get_data_loaders, "barrier_called", True)
```
