### ISSUE TITLE
Provide unittest with codecoverage report

### ISSUE THREAD

**Issue by Markus-Goetz** [Helmholtz-AI-Energy/propulate#20]
Automatically run unittests as a workflow, generate code coverage reports and upload them (e.g. codecov.io)

**Comment by mcw92** [comment]
Automated integration test and code coverage with `pytest` (see branch `base_integration_test` started by @oskar-taubert).
Also see: https://github.com/helmholtz-analytics/heat/blob/c43a2401786a8aa93d10617aafecb8a28114d2e9/.github/workflows/ci.yaml#L53

**Comment by oskar-taubert** [comment]
added basic tests
more will be added as features come online
