### ISSUE TITLE
All of the badges

### ISSUE THREAD

**Issue by Markus-Goetz** [Helmholtz-AI-Energy/propulate#21]
Add badges to the repository. Some that come to mind are:

    Test coverage
    Compatible Python version
    pip downloads
    code style
    contact

**Comment by mcw92** [comment]
Fix buggy code coverage badge in README. Locally, `coverage` returns the correct results including badge; however, the actual Github action returns a coverage of 0 %. We tried this action: 
- https://github.com/dbrgn/coverage-badge/blob/main/README.rst
- https://github.com/tj-actions/coverage-badge-py

**Comment by oskar-taubert** [comment]
done
