### ISSUE TITLE
MPI communicator handling: Parallelism on the level of single individuals

### ISSUE THREAD

**Issue by Markus-Goetz** [Helmholtz-AI-Energy/propulate#24]
Enable passing a specific MPI communicator to the evolution routine, defaulting to MPI_COMM_WORLD. Duplicate the communicator with MPI_Comm_dup beforehand.

**Comment by mcw92** [comment]
This is related to enabling parallelized evaluations, i.e., each evaluation of an individual is, e.g., a data-parallel training of a neural network using specific hyperparameters to be optimized. Requires one **"optimization" communicator** handling the optimization routine, with each rank corresponding to one worker evaluating an individual. Each of those optimization comm ranks (or workers) has another **"individual" communicator** attached which handles the parallelized evaluation of the individual itself. To communicate information between those two communicators, a worker's optimization comm rank must also be part of its individual comm as an "interface". This can be accomplished with splits or groups.
