### ISSUE TITLE
Integer parameters

### ISSUE THREAD

**Issue by oskar-taubert** [Helmholtz-AI-Energy/propulate#85]
Make clear and consistent, that integer parameters are sampled inclusively in the given interval limits e.g. {param: (1, 2)} can take the values 1 and 2, not just 1.

**Comment by oskar-taubert** [comment]
Also Init does range, so the default propagator is inconsistent in this

**Comment by oskar-taubert** [comment]
The bug is already fixed

**Comment by mcw92** [comment]
I thought that I already resolved this and also made it clear in the documentation: https://propulate.readthedocs.io/en/latest/tut_propulator.html 
Where do you think is missing information?
